# services/story-engine/Cargo.toml
[package]
name = "story-engine"
version.workspace = true
edition.workspace = true

[[bin]]
name = "story-engine"
path = "src/main.rs"

[dependencies]
fv-common.workspace = true
finalverse-protocol.workspace = true
axum.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
fv-health.workspace = true
service-registry.workspace = true
fv-events.workspace = true
chrono.workspace = true
reqwest.workspace = true
tower.workspace = true
tower-http = { workspace = true, features = ["cors"] }
warp = "0.3.7"
anyhow = "1.0.98"
env_logger = "0.11.8"
