# services/story-engine/Cargo.toml
[package]
name = "story-engine"
version.workspace = true
edition.workspace = true

[[bin]]
name = "story-engine"
path = "src/main.rs"

[dependencies]
finalverse-common.workspace = true
finalverse-protocol.workspace = true
axum.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
finalverse-health.workspace = true
finalverse-service-registry.workspace = true
chrono.workspace = true
reqwest.workspace = true
tower.workspace = true
tower-http = { workspace = true, features = ["cors"] }
