
# services/websocket-gateway/Cargo.toml
[package]
name = "websocket-gateway"
version.workspace = true
edition.workspace = true

[[bin]]
name = "websocket-gateway"
path = "src/main.rs"

[dependencies]
finalverse-core.workspace = true
finalverse-protocol.workspace = true
axum = { workspace = true, features = ["ws"] }
tokio = { workspace = true, features = ["full"] }
tower-http = { workspace = true, features = ["cors"] }
futures.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
finalverse-logging.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
finalverse-health.workspace = true
service-registry.workspace = true
reqwest = { workspace = true, features = ["json"] }
tower.workspace = true
