[package]
name = "finalverse-metobolism"
version.workspace = true
edition.workspace = true

[dependencies]
finalverse-core.workspace = true
tokio.workspace = true
serde = { workspace = true, features = ["derive"] }
rand.workspace = true
