# // Shared ecosystem logic
[package]
name = "finalverse-metabolism"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
uuid.workspace = true
rand.workspace = true
finalverse-core.workspace = true
