[package]
name = "fv-events"
version.workspace = true
edition.workspace = true
license = "Copyright Finalverse Inc."

[dependencies]
async-trait.workspace = true
anyhow.workspace = true
tokio.workspace = true
async-nats.workspace = true
futures-util.workspace = true

