[package]
name = "song-engine"
version.workspace = true
edition.workspace = true

[[bin]]
name = "song-engine"
path = "src/main.rs"

[dependencies]
fv-common.workspace = true
protocol.workspace = true
axum.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
health.workspace = true
finalverse-service-registry.workspace = true
tower.workspace = true
tower-http = { workspace = true, features = ["cors"] }
