[package]
name = "finalverse-audio-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["v4", "serde"] }
nalgebra.workspace = true
tokio = { workspace = true, features = ["full"] }

