[package]
name = "finalverse-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap = { version = "4.5.40", features = ["derive"] }
crossterm = "0.29.0"
env_logger = "0.11.8"
ratatui = "0.29.0"
serde.workspace = true
tokio.workspace = true
tokio-tungstenite = "0.26.2"
reqwest.workspace = true
finalverse-plugin = { path = "../services/plugin" }
once_cell.workspace = true

[[bin]]
name = "finalverse-server"
path = "src/main.rs"

[lib]
name = "finalverse_server"
path = "src/lib.rs"
