[package]
name = "events"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
anyhow.workspace = true
tokio.workspace = true
async-nats.workspace = true
futures-util.workspace = true

