[package]
name = "finalverse-logging"
version.workspace = true
edition.workspace = true

[dependencies]
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt", "json"] }
finalverse-config.workspace = true
once_cell.workspace = true
