[package]
name = "asset-service"
version.workspace = true
edition.workspace = true

[dependencies]
fv-common.workspace = true
protocol.workspace = true
health.workspace = true
finalverse-service-registry.workspace = true
axum.workspace = true
tokio.workspace = true
