[package]
name = "asset-service"
version.workspace = true
edition.workspace = true

[dependencies]
finalverse-core.workspace = true
finalverse-protocol.workspace = true
finalverse-health.workspace = true
service-registry.workspace = true
axum.workspace = true
tokio.workspace = true
