[package]
name = "asset-service"
version.workspace = true
edition.workspace = true

[dependencies]
finalverse-common = { path = "../../libs/common" }
finalverse-protocol = { path = "../../libs/protocol" }
finalverse-health.workspace = true
finalverse-service-registry.workspace = true
