[package]
name = "asset-service"
version.workspace = true
edition.workspace = true

[dependencies]
fv-common.workspace = true
finalverse-protocol.workspace = true
fv-health.workspace = true
service-registry.workspace = true
axum.workspace = true
tokio.workspace = true
