[package]
name = "behavior-ai"
version.workspace = true
edition.workspace = true

[dependencies]
finalverse-common.workspace = true
finalverse-protocol.workspace = true
finalverse-health.workspace = true
finalverse-service-registry.workspace = true
axum.workspace = true
tokio.workspace = true
