[package]
name = "harmony-service"
version.workspace = true
edition.workspace = true

[dependencies]
finalverse-common = { path = "../../libs/common" }
finalverse-protocol = { path = "../../libs/protocol" }
