[package]
name = "silence-service"
version.workspace = true
edition.workspace = true

[dependencies]
finalverse-core = { path = "../../crates/core" }
finalverse-protocol = { path = "../../crates/protocol" }
finalverse-health.workspace = true
service-registry.workspace = true
axum.workspace = true
tokio.workspace = true
finalverse-logging.workspace = true
tracing.workspace = true
