[package]
name = "silence-service"
version.workspace = true
edition.workspace = true

[dependencies]
finalverse-common = { path = "../../crates/finalverse-core" }
finalverse-protocol = { path = "../../crates/finalverse-protocol" }
finalverse-health.workspace = true
finalverse-service-registry.workspace = true
axum.workspace = true
tokio.workspace = true
