[package]
name = "procedural-gen"
version.workspace = true
edition.workspace = true

[dependencies]
fv-common = { path = "../../crates/fv-core" }
protocol = { path = "../../crates/protocol" }
health.workspace = true
service-registry.workspace = true
axum.workspace = true
tokio.workspace = true