[package]
name = "world3d-service"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
finalverse-world3d.workspace = true
dashmap = "7.0.0-rc2"
tokio = "1.45.1"
tonic = "0.13.1"
tracing = "0.1.41"
anyhow = "1.0.98"
tracing-subscriber = "0.3.19"
finalverse-logging.workspace = true
