[package]
name = "world-engine"
version.workspace = true
edition.workspace = true

[[bin]]
name = "world-engine"
path = "src/main.rs"

[dependencies]
finalverse-world-engine = { path = "../../crates/world-engine" }
finalverse-audio-core.workspace = true
redis.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
nalgebra.workspace = true
async-trait = "0.1.88"
tokio.workspace = true
warp = "0.3.7"
env_logger = "0.11.8"

