# // Manages the living world simulation
[package]
name = "world-engine"
version.workspace = true
edition.workspace = true

[[bin]]
name = "world-engine"
path = "src/main.rs"

[lib]
name = "world_engine"
path = "src/lib.rs"

[dependencies]
finalverse-audio-core.workspace = true
finalverse-core.workspace = true
finalverse-ecosystem.workspace = true
finalverse-grpc-client.workspace = true
finalverse-metobolism.workspace = true
finalverse-proto.workspace = true
finalverse-world3d.workspace = true

redis.workspace = true
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
rand.workspace = true
chrono.workspace = true
uuid.workspace = true
nalgebra.workspace = true

tonic.workspace = true
prost.workspace = true
prost-types.workspace = true
tokio-stream.workspace = true

async-trait = "0.1.88"
tokio.workspace = true
warp = "0.3.7"
finalverse-logging.workspace = true
anyhow = "1.0.98"
tracing.workspace = true

[build-dependencies]
tonic-build.workspace = true
