# // Manages the living world simulation
[package]
name = "world-engine"
version.workspace = true
edition.workspace = true

[[bin]]
name = "world-engine"
path = "src/main.rs"

[lib]
name = "world_engine"
path = "src/lib.rs"

[dependencies]
finalverse-world3d.workspace = true
finalverse-audio-core.workspace = true
finalverse-ecosystem.workspace = true
finalverse-metobolism.workspace = true
redis.workspace = true
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
rand.workspace = true
chrono.workspace = true
uuid.workspace = true
nalgebra.workspace = true
finalverse-core.workspace = true
async-trait = "0.1.88"
tokio.workspace = true
warp = "0.3.7"
env_logger = "0.11.8"
anyhow = "1.0.98"

